// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PresentacionWebApiCore.Context;

#nullable disable

namespace PresentacionWebApiCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230406181053_inicio")]
    partial class inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PresentacionWebApiCore.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("curso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Alumno ejemplar",
                            Email = "juanperez@mail.com",
                            Name = "Juan Perez",
                            curso = "Programación"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(2001, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Estudiante dedicada",
                            Email = "anagomez@mail.com",
                            Name = "Ana Gomez",
                            curso = "Matemáticas"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1999, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Buen compañero",
                            Email = "pedrorodriguez@mail.com",
                            Name = "Pedro Rodriguez",
                            curso = "Historia"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(2002, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Interesada en tecnología",
                            Email = "luisahernandez@mail.com",
                            Name = "Luisa Hernandez",
                            curso = "Informática"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(2003, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Alegre y optimista",
                            Email = "miguelsanchez@mail.com",
                            Name = "Miguel Sanchez",
                            curso = "Lengua"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
